# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 19:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(max_length=100)),
                ('data_e_hora_final', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.TextField(max_length=100)),
                ('data_e_hora_final', models.DateTimeField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contado',
            name='contagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Contagem'),
        ),
    ]
