# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20170217_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='contagem',
            name='movie',
            field=models.FileField(null=True, upload_to='static/video'),
        ),
    ]
