# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 20:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20170316_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contagem',
            name='nome_do_arquivo',
        ),
    ]
