# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 23:45
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_remove_contagem_nome_do_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('endereco', models.TextField(max_length=100)),
                ('alias', models.TextField(max_length=10)),
                ('contagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Contagem')),
            ],
        ),
    ]
