# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20170409_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagem',
            name='data_e_hora_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
