# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20170410_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contado',
            name='data_e_hora_final',
        ),
        migrations.RemoveField(
            model_name='contagem',
            name='data_e_hora_final',
        ),
        migrations.AddField(
            model_name='contado',
            name='data_e_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contado',
            name='destino',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='maps.Spot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contado',
            name='origem',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='maps.Spot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contagem',
            name='data_e_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
