# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170411_0346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='endereco',
            new_name='endereco_destino',
        ),
        migrations.RemoveField(
            model_name='contado',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='contado',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='x',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='y',
        ),
        migrations.AddField(
            model_name='contado',
            name='spot',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='maps.Spot'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='endereco_origem',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spot',
            name='geometry',
            field=models.TimeField(max_length=200, blank=True, null=True),
            preserve_default=False,
        ),
    ]
