# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_auto_20170412_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='geometry',
            field=models.TextField(max_length=2000),
        ),
    ]
