# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20170412_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('icon', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='spot',
            name='keys',
            field=models.ManyToManyField(to='maps.Key'),
        ),
    ]
