# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20170426_0540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_e_hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('movie', models.FileField(null=True, upload_to='static/video')),
            ],
            options={
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.RenameField(
            model_name='contagem',
            old_name='movie',
            new_name='movie_clip',
        ),
        migrations.AddField(
            model_name='movie',
            name='contagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Contagem'),
        ),
    ]
