# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0015_auto_20170503_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contagem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='contagem',
            name='data_e_hora',
        ),
        migrations.RemoveField(
            model_name='contagem',
            name='data_e_hora_inicio',
        ),
        migrations.RemoveField(
            model_name='contagem',
            name='movie_clip',
        ),
    ]
