# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20170505_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='bi',
            field=models.BooleanField(default=False),
        ),
    ]
