# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_movie_is_contado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='data_e_hora_inicio',
            field=models.DateTimeField(),
        ),
    ]
