# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20170618_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contagem',
            options={'ordering': ['endereco'], 'verbose_name_plural': 'Contagens'},
        ),
    ]
