# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_auto_20170621_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['data_e_hora_inicio'], 'verbose_name_plural': 'Vídeos'},
        ),
        migrations.AddField(
            model_name='movie',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
