# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 17:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20170707_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(default=None, srid=3875),
            preserve_default=False,
        ),
    ]
