# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:19
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_spot_geom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='geom',
            field=django.contrib.gis.db.models.fields.LineStringField(null=True, srid=3875),
        ),
    ]
