# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0025_auto_20170828_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='geom',
        ),
    ]
