# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-09 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0027_contagem_zoom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contagem',
            name='zoom',
            field=models.IntegerField(default=17),
        ),
    ]
